# Generated by Django 3.2 on 2021-04-17 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_access_token',
            field=models.CharField(default='erfwefev3', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_user_id',
            field=models.CharField(default='ferve', max_length=100),
            preserve_default=False,
        ),
    ]
