# Generated by Django 3.2 on 2021-04-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_customer_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price_setupfees',
            field=models.CharField(default='HI', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='prod_setupfees',
            field=models.CharField(default='HI', max_length=1000),
            preserve_default=False,
        ),
    ]
