# Generated by Django 3.2 on 2021-04-29 06:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    atomic = False
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0013_transactions_invoice_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='products',
            new_name='subsplans',
        ),
    ]
