# Generated by Django 3.2 on 2021-05-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_invoice_p_invoice_s'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='business_authentication',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='business_name',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='priv_url',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_authentication',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='tos_url',
            field=models.CharField(default='Hi', max_length=100),
            preserve_default=False,
        ),
    ]
