# Generated by Django 3.2 on 2021-05-04 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0017_auto_20210504_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='business_authentication',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='priv_url',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='stripe_authentication',
        ),
        migrations.RemoveField(
            model_name='seller',
            name='tos_url',
        ),
        migrations.CreateModel(
            name='business_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priv_url', models.CharField(max_length=100)),
                ('tos_url', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
