# Generated by Django 3.2 on 2021-05-05 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_auto_20210504_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsplans',
            name='interval_count',
            field=models.IntegerField(default=1),
        ),
    ]
