# Generated by Django 3.2 on 2021-05-05 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20210505_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsplans',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999999)]),
        ),
    ]
