# Generated by Django 3.2 on 2021-05-05 17:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_auto_20210505_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ot_product',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
