# Generated by Django 3.2 on 2021-05-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_transactions_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='stripe_acc_id',
        ),
    ]
