# Generated by Django 3.2 on 2021-05-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0030_remove_transactions_stripe_acc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='business_auth',
            name='stripe_id',
            field=models.CharField(default='hi', max_length=100),
            preserve_default=False,
        ),
    ]
