# Generated by Django 3.2 on 2021-12-03 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0031_business_auth_stripe_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business_auth',
            name='stripe_id',
        ),
    ]
